#!/usr/bin/env bash
# =============================================================================
# aragonteam — One-command redeploy script
#
# Performs a full redeploy cycle:
#   1. Backup current state
#   2. Pull latest code from git
#   3. Install dependencies
#   4. Build frontend (if applicable)
#   5. Reinstall systemd services
#   6. Verify deployment health
#
# Generated by web-deployer skill — 2026-07-20
#
# Usage:
#   sudo ./ops/deploy.sh                   # full redeploy
#   sudo ./ops/deploy.sh --skip-deps       # skip dependency install
#   sudo ./ops/deploy.sh --skip-build      # skip frontend build
#   sudo ./ops/deploy.sh --skip-backup     # skip backup step
#   sudo ./ops/deploy.sh --branch=staging  # pull from specific branch
#   sudo ./ops/deploy.sh --rollback        # rollback to last backup
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly BOLD='\033[1m'
readonly RESET='\033[0m'

log()   { echo -e "${CYAN}[$(date '+%H:%M:%S')]${RESET} $*"; }
ok()    { echo -e "${GREEN}[$(date '+%H:%M:%S')] OK${RESET} $*"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARN${RESET} $*"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR${RESET} $*" >&2; }
die()   { error "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
SKIP_DEPS=false
SKIP_BUILD=false
SKIP_BACKUP=false
BRANCH=""
ROLLBACK=false

for arg in "$@"; do
  case "$arg" in
    --skip-deps)     SKIP_DEPS=true ;;
    --skip-build)    SKIP_BUILD=true ;;
    --skip-backup)   SKIP_BACKUP=true ;;
    --branch=*)      BRANCH="${arg#*=}" ;;
    --rollback)      ROLLBACK=true ;;
    --help|-h)
      echo "Usage: sudo $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --skip-deps      Skip dependency installation"
      echo "  --skip-build     Skip frontend build step"
      echo "  --skip-backup    Skip backup creation"
      echo "  --branch=NAME    Pull from specific git branch"
      echo "  --rollback       Rollback to most recent backup"
      echo "  --help, -h       Show this help message"
      exit 0
      ;;
    *) warn "Unknown argument: $arg" ;;
  esac
done

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.env"

# Must run as root
if [[ "$(id -u)" -ne 0 ]]; then
  die "This script must be run with sudo. Usage: sudo $0"
fi

# Load configuration
if [[ ! -f "$CONFIG_FILE" ]]; then
  die "Configuration file not found: $CONFIG_FILE"
fi
# shellcheck source=config.env
source "$CONFIG_FILE"

PROJECT_NAME="${PROJECT_NAME:-aragonteam}"
DEPLOY_BACKUP_DIR="${PROJECT_DIR}/.deploy-backups"
TIMESTAMP="$(date '+%Y%m%d-%H%M%S')"

# Prefer the dedicated service account from config.env. Falling back to the
# invoking user keeps the script usable if no service account is configured.
RUN_USER="${RUN_USER:-${SUDO_USER:-$USER}}"

echo ""
echo -e "${BOLD}============================================================${RESET}"
echo -e "${BOLD}  ${PROJECT_NAME} — Deploy${RESET}"
echo -e "${BOLD}============================================================${RESET}"
echo ""

# ---------------------------------------------------------------------------
# Rollback mode
# ---------------------------------------------------------------------------
if [[ "$ROLLBACK" == true ]]; then
  log "Looking for most recent backup..."
  if [[ ! -d "$DEPLOY_BACKUP_DIR" ]]; then
    die "No backup directory found at $DEPLOY_BACKUP_DIR"
  fi

  LATEST_BACKUP=$(ls -td "$DEPLOY_BACKUP_DIR"/*/ 2>/dev/null | head -1) || true
  if [[ -z "$LATEST_BACKUP" ]]; then
    die "No backups found in $DEPLOY_BACKUP_DIR"
  fi

  log "Restoring from backup: $LATEST_BACKUP"

  # Restore git state
  if [[ -f "$LATEST_BACKUP/git-ref" ]]; then
    ref=$(cat "$LATEST_BACKUP/git-ref")
    log "Resetting to git ref: $ref"
    sudo -u "$RUN_USER" git -C "$PROJECT_DIR" checkout "$ref" 2>/dev/null || \
      sudo -u "$RUN_USER" git -C "$PROJECT_DIR" reset --hard "$ref"
  fi

  # Reinstall services
  log "Reinstalling services from rolled-back state..."
  "$SCRIPT_DIR/install.sh"

  ok "Rollback complete."
  exit 0
fi

# ---------------------------------------------------------------------------
# Step 1: Backup current state
# ---------------------------------------------------------------------------
if [[ "$SKIP_BACKUP" == false ]]; then
  log "Creating backup..."
  BACKUP_PATH="${DEPLOY_BACKUP_DIR}/${TIMESTAMP}"
  mkdir -p "$BACKUP_PATH"

  # Save git ref
  if [[ -d "$PROJECT_DIR/.git" ]]; then
    sudo -u "$RUN_USER" git -C "$PROJECT_DIR" rev-parse HEAD > "$BACKUP_PATH/git-ref" 2>/dev/null || true
    sudo -u "$RUN_USER" git -C "$PROJECT_DIR" diff > "$BACKUP_PATH/uncommitted.patch" 2>/dev/null || true
  fi

  # Save current config
  cp "$CONFIG_FILE" "$BACKUP_PATH/config.env.bak" 2>/dev/null || true

  ok "Backup created at $BACKUP_PATH"

  # Prune old backups (keep last 5)
  BACKUP_COUNT=$(ls -d "$DEPLOY_BACKUP_DIR"/*/ 2>/dev/null | wc -l) || true
  if [[ "$BACKUP_COUNT" -gt 5 ]]; then
    ls -td "$DEPLOY_BACKUP_DIR"/*/ | tail -n +6 | xargs rm -rf
    ok "Pruned old backups (kept last 5)."
  fi
else
  warn "Skipping backup (--skip-backup)."
fi

# ---------------------------------------------------------------------------
# Step 2: Pull latest code
# ---------------------------------------------------------------------------
log "Pulling latest code..."
if [[ -d "$PROJECT_DIR/.git" ]]; then
  if [[ -n "$BRANCH" ]]; then
    log "Switching to branch: $BRANCH"
    sudo -u "$RUN_USER" git -C "$PROJECT_DIR" fetch --all --prune
    sudo -u "$RUN_USER" git -C "$PROJECT_DIR" checkout "$BRANCH"
  fi
  sudo -u "$RUN_USER" git -C "$PROJECT_DIR" pull --ff-only || {
    warn "Fast-forward pull failed. Attempting merge pull..."
    sudo -u "$RUN_USER" git -C "$PROJECT_DIR" pull || die "Git pull failed. Resolve conflicts manually."
  }
  ok "Code updated to: $(sudo -u "$RUN_USER" git -C "$PROJECT_DIR" log --oneline -1)"
else
  warn "Not a git repository — skipping git pull."
fi

# ---------------------------------------------------------------------------
# Step 3: Install dependencies
# ---------------------------------------------------------------------------
if [[ "$SKIP_DEPS" == false ]]; then
  log "Installing dependencies..."
  if [[ -x "$SCRIPT_DIR/install-deps.sh" ]]; then
    sudo -u "$RUN_USER" "$SCRIPT_DIR/install-deps.sh" --skip-system
    ok "Dependencies installed."
  else
    warn "install-deps.sh not found or not executable, skipping."
  fi
else
  warn "Skipping dependency installation (--skip-deps)."
fi

# ---------------------------------------------------------------------------
# Step 4: Build frontend
# ---------------------------------------------------------------------------
if [[ "$SKIP_BUILD" == false ]]; then
  log "Building frontend..."
  FRONTEND_DIR="$PROJECT_DIR/frontend"
  if [[ "frontend" == "." ]]; then
    FRONTEND_DIR="$PROJECT_DIR"
  fi

  cd "$FRONTEND_DIR"
  sudo -u "$RUN_USER" env HOME="$(getent passwd "$RUN_USER" | cut -d: -f6)" \
    npm run build || die "Frontend build failed."
  ok "Frontend built successfully."
else
  warn "Skipping frontend build (--skip-build)."
fi

# ---------------------------------------------------------------------------
# Step 5: Reinstall systemd services
# ---------------------------------------------------------------------------
log "Reinstalling systemd services..."
"$SCRIPT_DIR/install.sh" --no-start
ok "Services reinstalled."

# ---------------------------------------------------------------------------
# Step 6: Start services and verify
# ---------------------------------------------------------------------------
log "Starting services..."

systemctl start ${PROJECT_NAME}-backend.service
log "Waiting for backend to be ready..."
BACKEND_READY=false
for _ in $(seq 1 30); do
  if curl -sf "${BACKEND_HEALTH_URL:-http://localhost:${BACKEND_PORT}/health}" >/dev/null 2>&1 || \
     curl -sf "${BACKEND_HEALTH_FALLBACK_URL:-http://localhost:${BACKEND_PORT}/}" >/dev/null 2>&1; then
    BACKEND_READY=true
    break
  fi
  sleep 1
done
if [[ "$BACKEND_READY" == true ]]; then
  ok "Backend is healthy."
else
  error "Backend did not respond within 30s."
  warn "Check: journalctl -u ${PROJECT_NAME}-backend -f"
  warn "To rollback: sudo $0 --rollback"
fi

systemctl start ${PROJECT_NAME}-frontend.service
log "Waiting for frontend to be ready..."
FRONTEND_READY=false
for _ in $(seq 1 30); do
  if curl -sf "${FRONTEND_HEALTH_URL:-http://localhost:${FRONTEND_PORT}/}" >/dev/null 2>&1; then
    FRONTEND_READY=true
    break
  fi
  sleep 1
done
if [[ "$FRONTEND_READY" == true ]]; then
  ok "Frontend is healthy."
else
  error "Frontend did not respond within 30s."
  warn "Check: journalctl -u ${PROJECT_NAME}-frontend -f"
  warn "To rollback: sudo $0 --rollback"
fi

# Start watchdog timer
systemctl start ${PROJECT_NAME}-watchdog.timer 2>/dev/null || true

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}============================================================${RESET}"
DEPLOY_STATUS="${GREEN}${BOLD}SUCCESS${RESET}"
if [[ "${BACKEND_READY:-true}" != true ]]; then
  DEPLOY_STATUS="${YELLOW}${BOLD}PARTIAL (backend unhealthy)${RESET}"
fi
if [[ "${FRONTEND_READY:-true}" != true ]]; then
  DEPLOY_STATUS="${YELLOW}${BOLD}PARTIAL (frontend unhealthy)${RESET}"
fi
echo -e "  Deploy result: ${DEPLOY_STATUS}"
echo -e "  Timestamp:     ${CYAN}${TIMESTAMP}${RESET}"
if [[ -d "$PROJECT_DIR/.git" ]]; then
  echo -e "  Git commit:    ${CYAN}$(sudo -u "$RUN_USER" git -C "$PROJECT_DIR" log --oneline -1)${RESET}"
fi
echo -e ""
echo -e "  ${BOLD}Quick commands:${RESET}"
echo -e "    ./ops/status.sh              # check service health"
echo -e "    ./ops/logs.sh -f             # follow all logs"
echo -e "    sudo ./ops/deploy.sh --rollback  # rollback to previous version"
echo -e "${BOLD}============================================================${RESET}"
echo ""
