#!/usr/bin/env bash
# =============================================================================
# aragonteam — Watchdog health check script
#
# Checks HTTP liveness of configured services. Restarts the corresponding
# systemd service after WATCHDOG_FAIL_THRESHOLD consecutive failures.
# Triggered by aragonteam-watchdog.timer.
#
# Generated by web-deployer skill — 2026-07-20
#
# Usage: ./ops/healthcheck.sh  (normally invoked by systemd, not manually)
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.env"

# ---------------------------------------------------------------------------
# Load configuration
# ---------------------------------------------------------------------------
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: Configuration file not found: $CONFIG_FILE" >&2
  exit 1
fi
# shellcheck source=config.env
source "$CONFIG_FILE"

# Apply defaults for any missing config values
PROJECT_NAME="${PROJECT_NAME:-aragonteam}"
BACKEND_PORT="${BACKEND_PORT:-5000}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
WATCHDOG_FAIL_THRESHOLD="${WATCHDOG_FAIL_THRESHOLD:-5}"
WATCHDOG_STATE_DIR="${WATCHDOG_STATE_DIR:-/tmp}"

# Health check URLs — configurable in config.env, with sensible defaults
BACKEND_HEALTH_URL="${BACKEND_HEALTH_URL:-http://localhost:${BACKEND_PORT}/health}"
BACKEND_HEALTH_FALLBACK_URL="${BACKEND_HEALTH_FALLBACK_URL:-http://localhost:${BACKEND_PORT}/}"
FRONTEND_HEALTH_URL="${FRONTEND_HEALTH_URL:-http://localhost:${FRONTEND_PORT}/}"

# ---------------------------------------------------------------------------
# Logging — writes to syslog via logger and stdout (captured by journal)
# ---------------------------------------------------------------------------
log() {
  logger -t ${PROJECT_NAME}-watchdog "$*"
  echo "$*"
}

# ---------------------------------------------------------------------------
# Concurrency protection via flock
# ---------------------------------------------------------------------------
LOCK_FILE="$WATCHDOG_STATE_DIR/${PROJECT_NAME}-watchdog.lock"
exec 200>"$LOCK_FILE"
if ! flock -n 200; then
  log "Another healthcheck is running, skipping."
  exit 0
fi

# ---------------------------------------------------------------------------
# Health check function
#
# Arguments:
#   $1 — service name (e.g., "backend", "frontend")
#   $2 — port number
#   $3 — systemd unit name (e.g., "myapp-backend.service")
#   $4 — primary health URL
#   $5 — fallback health URL (optional)
# ---------------------------------------------------------------------------
check_service() {
  local name="$1"
  local port="$2"
  local unit="$3"
  local url="$4"
  local fallback_url="${5:-}"
  local fail_file="$WATCHDOG_STATE_DIR/${PROJECT_NAME}-watchdog-${name}-failures"
  local http_code

  # Attempt primary health endpoint
  http_code=$(curl -sf -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 30 "$url" 2>/dev/null) || true

  if ! [[ "$http_code" =~ ^2 ]] && [[ -n "$fallback_url" ]]; then
    # Try fallback URL
    http_code=$(curl -sf -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 30 "$fallback_url" 2>/dev/null) || true
  fi

  if [[ "$http_code" =~ ^2 ]]; then
    # Success — reset failure counter
    echo "0" > "$fail_file"
    log "[OK] ${name} is healthy (${url})"
    return 0
  fi

  # HTTP check failed — but if port is still listening, process may be busy
  if ss -tlnH sport = :"$port" 2>/dev/null | grep -q .; then
    log "[WARN] ${name} HTTP check failed but port :${port} is listening — process may be busy, not counting as failure"
    return 0
  fi

  # Failure — increment counter
  local current_failures=0
  if [[ -f "$fail_file" ]]; then
    current_failures=$(cat "$fail_file" 2>/dev/null) || true
    if ! [[ "$current_failures" =~ ^[0-9]+$ ]]; then
      current_failures=0
    fi
  fi
  current_failures=$((current_failures + 1))
  echo "$current_failures" > "$fail_file"

  log "[FAIL] ${name} check failed (attempt ${current_failures}/${WATCHDOG_FAIL_THRESHOLD})"

  if [[ "$current_failures" -ge "$WATCHDOG_FAIL_THRESHOLD" ]]; then
    log "[RESTART] ${name} — restarting after ${WATCHDOG_FAIL_THRESHOLD} consecutive failures"
    if systemctl restart "$unit" 2>/dev/null; then
      log "[OK] ${name} restarted successfully"
    else
      log "[ERROR] ${name} restart failed"
    fi
    echo "0" > "$fail_file"
  fi
}

# ---------------------------------------------------------------------------
# Run health checks
# ---------------------------------------------------------------------------
check_service "backend" "$BACKEND_PORT" "${PROJECT_NAME}-backend.service" \
  "$BACKEND_HEALTH_URL" "$BACKEND_HEALTH_FALLBACK_URL"

check_service "frontend" "$FRONTEND_PORT" "${PROJECT_NAME}-frontend.service" \
  "$FRONTEND_HEALTH_URL" ""
