#!/usr/bin/env bash
# =============================================================================
# aragonteam — One-click systemd service installer
#
# Installs project services as systemd units with optional watchdog timer,
# logrotate configuration, and Nginx reverse proxy.
#
# Generated by web-deployer skill — 2026-07-20
#
# Usage: sudo ./ops/install.sh [--no-start] [--no-watchdog] [--no-logrotate]
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly BOLD='\033[1m'
readonly RESET='\033[0m'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()   { echo -e "${CYAN}[$(date '+%H:%M:%S')]${RESET} $*"; }
ok()    { echo -e "${GREEN}[$(date '+%H:%M:%S')] OK${RESET} $*"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARN${RESET} $*"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR${RESET} $*" >&2; }
die()   { error "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
NO_START=false
NO_WATCHDOG=false
NO_LOGROTATE=false
NO_NGINX=false

for arg in "$@"; do
  case "$arg" in
    --no-start)     NO_START=true ;;
    --no-watchdog)  NO_WATCHDOG=true ;;
    --no-logrotate) NO_LOGROTATE=true ;;
    --no-nginx)     NO_NGINX=true ;;
    --domain=*)     NGINX_DOMAIN_ARG="${arg#*=}" ;;
    --help|-h)
      echo "Usage: sudo $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --no-start       Install without starting services"
      echo "  --no-watchdog    Skip watchdog timer installation"
      echo "  --no-logrotate   Skip logrotate configuration"
      echo "  --no-nginx       Skip Nginx reverse proxy configuration"
      echo "  --domain=DOMAIN  Override NGINX_DOMAIN from config.env"
      echo "  --help, -h       Show this help message"
      exit 0
      ;;
    *) warn "Unknown argument: $arg" ;;
  esac
done

# ---------------------------------------------------------------------------
# Resolve script and project directories
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/templates"
CONFIG_FILE="$SCRIPT_DIR/config.env"

if [[ ! -f "$CONFIG_FILE" ]]; then
  die "Configuration file not found: $CONFIG_FILE"
fi
# shellcheck source=config.env
source "$CONFIG_FILE"

# ---------------------------------------------------------------------------
# Step 1: Prerequisites
# ---------------------------------------------------------------------------
log "Checking prerequisites..."

# Must run as root / under sudo
if [[ "$(id -u)" -ne 0 ]]; then
  die "This script must be run with sudo. Usage: sudo $0"
fi

# ---------------------------------------------------------------------------
# Resolve node binary — sudo resets PATH so nvm/user-installed node is invisible.
# ---------------------------------------------------------------------------
resolve_node() {
  # 1. Explicit override from config.env
  if [[ -n "${NODE_BIN:-}" && -x "${NODE_BIN}" ]]; then
    echo "$NODE_BIN"; return 0
  fi

  # 2. Ask the original user's interactive login shell (nvm/conda/pyenv)
  if [[ -n "${SUDO_USER:-}" ]]; then
    local user_node
    user_node="$(sudo -u "$SUDO_USER" bash -ilc 'command -v node' 2>/dev/null)" || true
    if [[ -n "$user_node" && -x "$user_node" ]]; then
      echo "$user_node"; return 0
    fi
  fi

  # 3. Scan nvm directories (latest version first)
  if [[ -n "${SUDO_USER:-}" ]]; then
    local user_home
    user_home="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
    local candidate
    for candidate in $(ls -rd "$user_home"/.nvm/versions/node/*/bin/node 2>/dev/null); do
      if [[ -x "$candidate" ]]; then
        echo "$candidate"; return 0
      fi
    done
  fi

  # 4. Current (sudo) PATH
  command -v node 2>/dev/null && return 0

  # 5. Common system locations
  local candidate
  for candidate in /usr/local/bin/node /usr/bin/node /snap/bin/node; do
    if [[ -x "$candidate" ]]; then
      echo "$candidate"; return 0
    fi
  done

  return 1
}

DETECTED_NODE="$(resolve_node)" || die "Node.js is not installed. Install it or set NODE_BIN in config.env."
PATH="$(dirname "$DETECTED_NODE"):$PATH"
export PATH

# ---------------------------------------------------------------------------
# Resolve Python — check venv, conda, system
# ---------------------------------------------------------------------------
resolve_python() {
  # 1. Explicit override from config.env
  if [[ -n "${VENV_PYTHON:-}" && -x "${VENV_PYTHON}" ]]; then
    echo "$VENV_PYTHON"; return 0
  fi

  # 2. Project venv
  local venv_dirs=("backend" ".")
  for dir in "${venv_dirs[@]}"; do
    local venv_path="$PROJECT_DIR/$dir/.venv/bin/python"
    if [[ -x "$venv_path" ]]; then
      echo "$venv_path"; return 0
    fi
  done

  # 3. Conda env (ask original user's shell)
  if [[ -n "${SUDO_USER:-}" ]]; then
    local user_python
    user_python="$(sudo -u "$SUDO_USER" bash -ilc 'command -v python3' 2>/dev/null)" || true
    if [[ -n "$user_python" && -x "$user_python" ]]; then
      echo "$user_python"; return 0
    fi
  fi

  # 4. System Python
  command -v python3 2>/dev/null && return 0
  return 1
}

DETECTED_PYTHON="$(resolve_python)" || die "Python 3 is not installed. Install it or set VENV_PYTHON in config.env."

# Check other required tools
command -v curl >/dev/null 2>&1 || die "curl is not installed."

# Check frontend build artifacts
if [[ -n ".next" && ! -d "$PROJECT_DIR/frontend/.next" ]]; then
  warn "Build output directory '.next' not found. You may need to run the build command first."
fi

# Check Python venv
VENV_PYTHON="${DETECTED_PYTHON}"
if [[ ! -x "$VENV_PYTHON" ]]; then
  die "Python binary not found at $VENV_PYTHON"
fi

ok "All prerequisites satisfied."

# ---------------------------------------------------------------------------
# Step 2: Detect runtime environment
# ---------------------------------------------------------------------------
log "Detecting runtime environment..."

RUN_USER="${RUN_USER:-${SUDO_USER:-$USER}}"
RUN_GROUP="${RUN_GROUP:-$(id -gn "$RUN_USER")}"

NODE_BIN="$DETECTED_NODE"
USER_DATA_DIR="${USER_DATA_DIR:-/var/lib/aragonteam}"

# Build PATH for systemd services
USER_LOGIN_PATH="$(sudo -u "$RUN_USER" bash -ilc 'echo $PATH' 2>/dev/null)" || true
PATH_DIRS="${USER_LOGIN_PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}"
PATH_DIRS="$(dirname "$NODE_BIN"):$PATH_DIRS"
PATH_DIRS="$(dirname "$VENV_PYTHON"):$PATH_DIRS"

ok "User=$RUN_USER  Group=$RUN_GROUP"
ok "Project=$PROJECT_DIR"
ok "Python=$VENV_PYTHON"
ok "Node=$NODE_BIN"
ok "UserData=$USER_DATA_DIR"

# ---------------------------------------------------------------------------
# Step 3: Load configuration
# ---------------------------------------------------------------------------
ok "Configuration loaded from $CONFIG_FILE"

# ---------------------------------------------------------------------------
# Step 4: Stop existing services (idempotent)
# ---------------------------------------------------------------------------
log "Stopping existing aragonteam services (if any)..."
systemctl stop aragonteam-watchdog.timer   2>/dev/null || true
systemctl stop aragonteam-watchdog.service 2>/dev/null || true
systemctl stop aragonteam-frontend.service 2>/dev/null || true
systemctl stop aragonteam-backend.service  2>/dev/null || true
systemctl disable aragonteam-watchdog.timer   2>/dev/null || true
systemctl disable aragonteam-frontend.service 2>/dev/null || true
systemctl disable aragonteam-backend.service  2>/dev/null || true
ok "Existing services stopped and disabled."

# ---------------------------------------------------------------------------
# Step 5: Install systemd unit files via template substitution
# ---------------------------------------------------------------------------
log "Installing systemd unit files..."

install_template() {
  local src="$1"
  local dest="$2"

  if [[ ! -f "$src" ]]; then
    die "Template not found: $src"
  fi

  # The web-deployer two-pass renderer has already resolved this project's
  # unit files. Install them verbatim to avoid a second, overly broad sed pass.
  install -m 0644 "$src" "$dest"
  ok "Installed: $dest"
  return 0

  sed \
    -e "s|aragonteam|${PROJECT_NAME}|g" \
    -e "s|/opt/aragonteam|${PROJECT_DIR}|g" \
    -e "s|aragonteam|${RUN_USER}|g" \
    -e "s|aragonteam|${RUN_GROUP}|g" \
    -e "s|5000|${BACKEND_PORT:-}|g" \
    -e "s|3000|${FRONTEND_PORT:-}|g" \
    -e "s|/var/lib/aragonteam|${USER_DATA_DIR}|g" \
    -e "s|60|${WATCHDOG_INTERVAL}|g" \
    -e "s|5|${WATCHDOG_FAIL_THRESHOLD:-5}|g" \
    -e "s|/opt/aragonteam/backend/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin|${PATH_DIRS}|g" \
    -e "s|/opt/aragonteam/backend/.venv/bin/python|${VENV_PYTHON:-}|g" \
    -e "s|/usr/bin/node|${NODE_BIN:-}|g" \
    -e "s|flask|${BACKEND_FRAMEWORK:-}|g" \
    -e "s|nextjs|${FRONTEND_FRAMEWORK:-}|g" \
    -e "s|/opt/aragonteam/backend/.venv/bin/gunicorn --workers 1 --threads 4 --bind 127.0.0.1:5000 --access-logfile - --error-logfile - app:app|${BACKEND_START:-}|g" \
    -e "s|/usr/bin/npm run start -- --hostname 127.0.0.1 --port 3000|${FRONTEND_START:-}|g" \
    -e "s|backend|${BACKEND_SUBDIRECTORY:-}|g" \
    -e "s|frontend|${FRONTEND_SUBDIRECTORY:-}|g" \
    -e "s|.next|${FRONTEND_BUILD_OUTPUT:-}|g" \
    -e "s|http://127.0.0.1:5000/api/health|${BACKEND_HEALTH_URL:-}|g" \
    -e "s|http://127.0.0.1:5000/api/health|${BACKEND_HEALTH_FALLBACK_URL:-}|g" \
    -e "s|http://127.0.0.1:3000/|${FRONTEND_HEALTH_URL:-}|g" \
    -e "s|logs|${LOG_DIR:-logs}|g" \
    -e "s|50M|${LOG_MAX_SIZE:-50M}|g" \
    -e "s|7|${LOG_ROTATE_COUNT:-7}|g" \
    "$src" > "$dest"

  ok "Installed: $dest"
}

install_template "$TEMPLATE_DIR/aragonteam-backend.service" \
  "/etc/systemd/system/aragonteam-backend.service"

install_template "$TEMPLATE_DIR/aragonteam-frontend.service" \
  "/etc/systemd/system/aragonteam-frontend.service"

# ---------------------------------------------------------------------------
# Step 6: Install watchdog (unless --no-watchdog)
# ---------------------------------------------------------------------------
if [[ "$NO_WATCHDOG" == false ]]; then
  log "Installing watchdog service and timer..."

  install_template "$TEMPLATE_DIR/aragonteam-watchdog.service" \
    "/etc/systemd/system/aragonteam-watchdog.service"

  install_template "$TEMPLATE_DIR/aragonteam-watchdog.timer" \
    "/etc/systemd/system/aragonteam-watchdog.timer"

  chmod +x "$SCRIPT_DIR/healthcheck.sh"
  ok "Watchdog installed."
else
  warn "Skipping watchdog installation (--no-watchdog)."
fi

# ---------------------------------------------------------------------------
# Step 7: Install logrotate configuration (unless --no-logrotate)
# ---------------------------------------------------------------------------
if [[ "$NO_LOGROTATE" == false ]]; then
  log "Installing logrotate configuration..."

  if [[ -f "$TEMPLATE_DIR/aragonteam-logrotate" ]]; then
    sed \
      -e "s|/opt/aragonteam|${PROJECT_DIR}|g" \
      -e "s|logs|${LOG_DIR}|g" \
      -e "s|50M|${LOG_MAX_SIZE}|g" \
      -e "s|7|${LOG_ROTATE_COUNT}|g" \
      -e "s|aragonteam|${RUN_USER}|g" \
      -e "s|aragonteam|${RUN_GROUP}|g" \
      "$TEMPLATE_DIR/aragonteam-logrotate" > "/etc/logrotate.d/aragonteam"
    ok "Logrotate config installed to /etc/logrotate.d/aragonteam"
  else
    warn "Logrotate template not found, skipping."
  fi
else
  warn "Skipping logrotate installation (--no-logrotate)."
fi

# ---------------------------------------------------------------------------
# Step 8: Configure Nginx reverse proxy (unless --no-nginx)
# ---------------------------------------------------------------------------
configure_nginx() {
  if [[ "$NO_NGINX" == true ]]; then
    warn "Skipping Nginx configuration (--no-nginx)."
    return 0
  fi

  local domain="${NGINX_DOMAIN_ARG:-${NGINX_DOMAIN:-}}"
  local site_name="${NGINX_SITE_NAME:-aragonteam}"
  local nginx_conf="/etc/nginx/sites-available/$site_name"
  local nginx_enabled="/etc/nginx/sites-enabled/$site_name"

  if ! command -v nginx >/dev/null 2>&1; then
    warn "Nginx is not installed. Skipping reverse proxy configuration."
    return 0
  fi

  # Auto-detect domain from existing config if not specified
  if [[ -z "$domain" && -f "$nginx_conf" ]]; then
    domain=$(grep -oP 'server_name\s+\K[^;]+' "$nginx_conf" 2>/dev/null | head -1 | xargs) || true
  fi

  if [[ -z "$domain" ]]; then
    warn "NGINX_DOMAIN not set in config.env and no existing config found."
    warn "Skipping Nginx setup. Set NGINX_DOMAIN or use --domain=YOUR_DOMAIN."
    return 0
  fi

  # Backup existing config
  if [[ -f "$nginx_conf" ]]; then
    if grep -q "# aragonteam nginx config v1" "$nginx_conf"; then
      ok "Nginx config already has aragonteam settings (v1). Skipping."
      return 0
    fi
    cp "$nginx_conf" "${nginx_conf}.bak.$(date '+%Y%m%d%H%M%S')"
    log "Backed up existing Nginx config."
  fi

  log "Configuring Nginx reverse proxy for ${BOLD}${domain}${RESET}..."

  # Detect SSL certificates
  local primary_domain
  primary_domain=$(echo "$domain" | awk '{print $1}')
  local ssl_cert="" ssl_key="" ssl_extra=""

  if [[ -f "/etc/letsencrypt/live/${primary_domain}/fullchain.pem" ]]; then
    ssl_cert="/etc/letsencrypt/live/${primary_domain}/fullchain.pem"
    ssl_key="/etc/letsencrypt/live/${primary_domain}/privkey.pem"
    if [[ -f "/etc/letsencrypt/options-ssl-nginx.conf" ]]; then
      ssl_extra="    include /etc/letsencrypt/options-ssl-nginx.conf;"$'\n'
    fi
    if [[ -f "/etc/letsencrypt/ssl-dhparams.pem" ]]; then
      ssl_extra="${ssl_extra}    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"$'\n'
    fi
    ok "Detected Let's Encrypt SSL for ${primary_domain}."
  elif [[ -f "$nginx_conf" ]]; then
    ssl_cert=$(grep -oP 'ssl_certificate\s+\K[^;]+' "$nginx_conf" 2>/dev/null | head -1 | xargs) || true
    ssl_key=$(grep -oP 'ssl_certificate_key\s+\K[^;]+' "$nginx_conf" 2>/dev/null | head -1 | xargs) || true
  fi

  # Choose template and render
  local template
  if [[ -n "$ssl_cert" && -n "$ssl_key" ]]; then
    template="$TEMPLATE_DIR/aragonteam-nginx"
  else
    template="$TEMPLATE_DIR/aragonteam-nginx-http"
    warn "No SSL certificate found. Using HTTP-only config."
    warn "Run: sudo certbot --nginx -d ${primary_domain} to enable HTTPS."
  fi

  if [[ ! -f "$template" ]]; then
    warn "Nginx template not found at $template. Skipping."
    return 0
  fi

  local rendered
  # The selected HTTP template is already fully rendered by web-deployer's
  # two-pass renderer. A second sed pass creates empty SSL expressions.
  rendered=$(cat "$template")

  printf '%s\n' "$rendered" > "$nginx_conf"

  if [[ ! -e "$nginx_enabled" ]]; then
    ln -s "$nginx_conf" "$nginx_enabled"
  fi

  # Clean duplicate domain blocks from default site
  local default_conf="/etc/nginx/sites-enabled/default"
  if [[ -f "$default_conf" ]] && grep -q "$primary_domain" "$default_conf" 2>/dev/null; then
    warn "Removing duplicate ${primary_domain} blocks from default site..."
    cp "$default_conf" "${default_conf}.bak.$(date '+%Y%m%d%H%M%S')"
    local tmp_clean
    tmp_clean=$(mktemp)
    awk -v domain="$primary_domain" '
      /^server[ \t]*\{/ { block=""; depth=0; in_block=1 }
      in_block { block = block $0 "\n"; depth += gsub(/{/, "{"); depth -= gsub(/}/, "}"); if (depth<=0) { if (block !~ domain) printf "%s", block; in_block=0; block="" } next }
      { print }
    ' "$default_conf" > "$tmp_clean" && mv "$tmp_clean" "$default_conf"
  fi

  find /etc/nginx/sites-enabled/ -name "*.bak*" -delete 2>/dev/null || true

  if nginx -t 2>&1; then
    systemctl reload nginx
    ok "Nginx configured and reloaded for ${BOLD}${domain}${RESET}."
  else
    error "Nginx config test failed! Check: nginx -t"
    local latest_backup
    latest_backup=$(ls -t "${nginx_conf}.bak."* 2>/dev/null | head -1) || true
    if [[ -n "$latest_backup" ]]; then
      cp "$latest_backup" "$nginx_conf"
      nginx -t 2>/dev/null && systemctl reload nginx && warn "Restored previous Nginx config."
    fi
  fi
}

configure_nginx

# ---------------------------------------------------------------------------
# Step 9: Reload systemd and enable services
# ---------------------------------------------------------------------------
log "Reloading systemd daemon..."
systemctl daemon-reload
ok "systemd daemon reloaded."

log "Enabling services..."
systemctl enable aragonteam-backend.service
systemctl enable aragonteam-frontend.service
if [[ "$NO_WATCHDOG" == false ]]; then
  systemctl enable aragonteam-watchdog.timer
fi
ok "Services enabled for boot."

# ---------------------------------------------------------------------------
# Step 10: Start services (unless --no-start)
# ---------------------------------------------------------------------------
if [[ "$NO_START" == false ]]; then
  log "Starting aragonteam backend..."
  systemctl start aragonteam-backend.service

  log "Waiting for backend to be ready..."
  BACKEND_READY=false
  for _ in $(seq 1 30); do
    if curl -sf "${BACKEND_HEALTH_URL:-http://localhost:${BACKEND_PORT}/health}" >/dev/null 2>&1 || \
       curl -sf "${BACKEND_HEALTH_FALLBACK_URL:-http://localhost:${BACKEND_PORT}/}" >/dev/null 2>&1; then
      BACKEND_READY=true
      break
    fi
    sleep 1
  done
  if [[ "$BACKEND_READY" == true ]]; then
    ok "Backend is ready at http://localhost:${BACKEND_PORT}"
  else
    warn "Backend did not respond within 30s. Check: journalctl -u aragonteam-backend -f"
  fi

  log "Starting aragonteam frontend..."
  systemctl start aragonteam-frontend.service

  log "Waiting for frontend to be ready..."
  FRONTEND_READY=false
  for _ in $(seq 1 30); do
    if curl -sf "${FRONTEND_HEALTH_URL:-http://localhost:${FRONTEND_PORT}/}" >/dev/null 2>&1; then
      FRONTEND_READY=true
      break
    fi
    sleep 1
  done
  if [[ "$FRONTEND_READY" == true ]]; then
    ok "Frontend is ready at http://localhost:${FRONTEND_PORT}"
  else
    warn "Frontend did not respond within 30s. Check: journalctl -u aragonteam-frontend -f"
  fi

  if [[ "$NO_WATCHDOG" == false ]]; then
    log "Starting watchdog timer..."
    systemctl start aragonteam-watchdog.timer
    ok "Watchdog timer started."
  fi
else
  warn "Skipping service start (--no-start). Start manually with:"
  warn "  systemctl start aragonteam-backend aragonteam-frontend aragonteam-watchdog.timer"
fi

# ---------------------------------------------------------------------------
# Step 11: Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}============================================================${RESET}"
echo -e "${GREEN}${BOLD}  aragonteam systemd installation complete${RESET}"
echo -e "${BOLD}============================================================${RESET}"
echo -e "  Backend  :  aragonteam-backend.service  (port ${CYAN}${BACKEND_PORT}${RESET})"
echo -e "  Frontend :  aragonteam-frontend.service (port ${CYAN}${FRONTEND_PORT}${RESET})"
if [[ "$NO_WATCHDOG" == false ]]; then
  echo -e "  Watchdog :  aragonteam-watchdog.timer   (every ${CYAN}${WATCHDOG_INTERVAL}s${RESET})"
fi
NGINX_SHOW_DOMAIN="${NGINX_DOMAIN_ARG:-${NGINX_DOMAIN:-}}"
if [[ -n "$NGINX_SHOW_DOMAIN" && "$NO_NGINX" == false ]]; then
  echo -e "  Nginx    :  ${CYAN}${NGINX_SHOW_DOMAIN}${RESET}  (reverse proxy with SSE support)"
fi
echo -e ""
echo -e "  ${BOLD}Useful commands:${RESET}"
echo -e "    systemctl status aragonteam-backend"
echo -e "    systemctl status aragonteam-frontend"
echo -e "    journalctl -u aragonteam-backend -f"
echo -e "    journalctl -u aragonteam-frontend -f"
echo -e "    sudo ./ops/uninstall.sh"
echo -e "${BOLD}============================================================${RESET}"
echo ""
