#!/usr/bin/env bash
# =============================================================================
# aragonteam — Dependency installer
#
# Installs all project dependencies in the current environment.
# Supports Python (pip/pipenv/poetry/conda), Node.js (npm/yarn/pnpm),
# and optional framework-specific dependencies.
#
# Generated by web-deployer skill — 2026-07-20
#
# Usage:
#   ./ops/install-deps.sh                 # install everything
#   ./ops/install-deps.sh --skip-system   # skip apt packages (no sudo needed)
#   ./ops/install-deps.sh --only python   # only Python deps
#   ./ops/install-deps.sh --only node     # only Node.js deps
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly BOLD='\033[1m'
readonly RESET='\033[0m'

log()   { echo -e "${CYAN}[$(date '+%H:%M:%S')]${RESET} $*"; }
ok()    { echo -e "${GREEN}[$(date '+%H:%M:%S')] OK${RESET} $*"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARN${RESET} $*"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR${RESET} $*" >&2; }
die()   { error "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
SKIP_SYSTEM=false
ONLY=""

for arg in "$@"; do
  case "$arg" in
    --skip-system|-s) SKIP_SYSTEM=true ;;
    --only)           ;; # value handled by positional fallthrough
    python|node)
      ONLY="$arg" ;;
    --help|-h)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --skip-system, -s   Skip system packages (no sudo required)"
      echo "  --only <component>  Install only: python, node"
      echo "  --help, -h          Show this help"
      exit 0
      ;;
    *) warn "Unknown argument: $arg" ;;
  esac
done

# ---------------------------------------------------------------------------
# Resolve project directory
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load config.env for framework-specific settings
CONFIG_FILE="$SCRIPT_DIR/config.env"
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck source=config.env
  source "$CONFIG_FILE"
fi

# ---------------------------------------------------------------------------
# Detect available tools
# ---------------------------------------------------------------------------
log "Detecting environment..."

HAVE_PYTHON=false
HAVE_PIP=false
HAVE_NODE=false
HAVE_NPM=false
HAVE_YARN=false
HAVE_PNPM=false
HAVE_SUDO=false

command -v python3 >/dev/null 2>&1 && HAVE_PYTHON=true || true
command -v pip     >/dev/null 2>&1 && HAVE_PIP=true || \
  { command -v pip3 >/dev/null 2>&1 && HAVE_PIP=true; } || true
command -v node    >/dev/null 2>&1 && HAVE_NODE=true  || true
command -v npm     >/dev/null 2>&1 && HAVE_NPM=true   || true
command -v yarn    >/dev/null 2>&1 && HAVE_YARN=true  || true
command -v pnpm    >/dev/null 2>&1 && HAVE_PNPM=true  || true
sudo -n true 2>/dev/null          && HAVE_SUDO=true || true

# Determine pip command
PIP_CMD=""
if command -v pip >/dev/null 2>&1; then
  PIP_CMD="pip"
elif command -v pip3 >/dev/null 2>&1; then
  PIP_CMD="pip3"
fi

# Show environment info
PYTHON_INFO=""
if [[ "$HAVE_PYTHON" == true ]]; then
  PYTHON_INFO="$(python3 --version) @ $(command -v python3)"
fi
NODE_INFO=""
if [[ "$HAVE_NODE" == true ]]; then
  NODE_INFO="$(node --version) @ $(command -v node)"
fi
CONDA_INFO="${CONDA_DEFAULT_ENV:-none}"

echo -e "  Python:  ${CYAN}${PYTHON_INFO:-not found}${RESET}"
echo -e "  Node.js: ${CYAN}${NODE_INFO:-not found}${RESET}"
echo -e "  Conda:   ${CYAN}${CONDA_INFO}${RESET}"
echo -e "  sudo:    ${CYAN}${HAVE_SUDO}${RESET}"
echo ""

should_run() {
  [[ -z "$ONLY" || "$ONLY" == "$1" ]]
}

ERRORS=0
TOTAL_STEPS=0

# Count Python as a step
TOTAL_STEPS=$((TOTAL_STEPS + 1))
# Count Node as a step
TOTAL_STEPS=$((TOTAL_STEPS + 1))

STEP=0

# ---------------------------------------------------------------------------
# Python dependencies
# ---------------------------------------------------------------------------
if should_run python; then
  STEP=$((STEP + 1))
  log "${BOLD}[${STEP}/${TOTAL_STEPS}] Python dependencies${RESET}"

  if [[ "$HAVE_PYTHON" == false ]]; then
    error "Python 3 not found. Install Python 3.8+ first."
    ERRORS=$((ERRORS + 1))
  elif [[ -z "$PIP_CMD" ]]; then
    error "pip not found. Install pip: python3 -m ensurepip --upgrade"
    ERRORS=$((ERRORS + 1))
  else
    PYTHON_DIR="$PROJECT_DIR/backend"
    if [[ "backend" == "." ]]; then
      PYTHON_DIR="$PROJECT_DIR"
    fi

    # Create venv if it does not exist
    if [[ ! -d "$PYTHON_DIR/.venv" ]]; then
      log "Creating Python virtual environment..."
      python3 -m venv "$PYTHON_DIR/.venv"
      ok "venv created at $PYTHON_DIR/.venv"
    fi

    # Activate venv
    # shellcheck source=/dev/null
    source "$PYTHON_DIR/.venv/bin/activate" 2>/dev/null || true

    # Upgrade pip
    log "Upgrading pip..."
    "$PIP_CMD" install --upgrade pip --quiet 2>&1 | tail -2 || true

    # Install requirements based on package manager
    case "pip" in
      pipenv)
        if command -v pipenv >/dev/null 2>&1; then
          log "Installing Python packages via pipenv..."
          cd "$PYTHON_DIR" && pipenv install
        else
          warn "pipenv not found, falling back to pip + requirements.txt"
          if [[ -f "$PYTHON_DIR/requirements.txt" ]]; then
            "$PIP_CMD" install -r "$PYTHON_DIR/requirements.txt" --quiet
          fi
        fi
        ;;
      poetry)
        if command -v poetry >/dev/null 2>&1; then
          log "Installing Python packages via poetry..."
          cd "$PYTHON_DIR" && poetry install --no-interaction
        else
          warn "poetry not found, falling back to pip + requirements.txt"
          if [[ -f "$PYTHON_DIR/requirements.txt" ]]; then
            "$PIP_CMD" install -r "$PYTHON_DIR/requirements.txt" --quiet
          fi
        fi
        ;;
      conda)
        if command -v conda >/dev/null 2>&1; then
          log "Installing Python packages via conda..."
          if [[ -f "$PYTHON_DIR/environment.yml" ]]; then
            conda env update -f "$PYTHON_DIR/environment.yml" --prune
          elif [[ -f "$PYTHON_DIR/requirements.txt" ]]; then
            "$PIP_CMD" install -r "$PYTHON_DIR/requirements.txt" --quiet
          fi
        else
          warn "conda not found, falling back to pip + requirements.txt"
          if [[ -f "$PYTHON_DIR/requirements.txt" ]]; then
            "$PIP_CMD" install -r "$PYTHON_DIR/requirements.txt" --quiet
          fi
        fi
        ;;
      *)
        # Default: pip
        if [[ -f "$PYTHON_DIR/requirements.txt" ]]; then
          log "Installing Python packages from requirements.txt..."
          "$PIP_CMD" install -r "$PYTHON_DIR/requirements.txt" --quiet
        elif [[ -f "$PYTHON_DIR/pyproject.toml" ]]; then
          log "Installing Python packages from pyproject.toml..."
          "$PIP_CMD" install -e "$PYTHON_DIR" --quiet
        else
          warn "No Python dependency file found in $PYTHON_DIR, skipping."
        fi
        ;;
    esac
    ok "Python packages installed."
  fi
  echo ""
fi

# ---------------------------------------------------------------------------
# Node.js dependencies
# ---------------------------------------------------------------------------
if should_run node; then
  STEP=$((STEP + 1))
  log "${BOLD}[${STEP}/${TOTAL_STEPS}] Node.js dependencies${RESET}"

  if [[ "$HAVE_NODE" == false ]]; then
    error "Node.js not found. Install Node.js 18+ first."
    ERRORS=$((ERRORS + 1))
  else
    NODE_DIR="$PROJECT_DIR/frontend"
    if [[ "frontend" == "." ]]; then
      NODE_DIR="$PROJECT_DIR"
    fi

    cd "$NODE_DIR"

    case "npm" in
      yarn)
        if [[ "$HAVE_YARN" == true ]]; then
          log "Installing Node.js packages via yarn..."
          yarn install --frozen-lockfile 2>&1 | tail -5
        else
          warn "yarn not found, falling back to npm"
          npm ci --loglevel=error
        fi
        ;;
      pnpm)
        if [[ "$HAVE_PNPM" == true ]]; then
          log "Installing Node.js packages via pnpm..."
          pnpm install --frozen-lockfile 2>&1 | tail -5
        else
          warn "pnpm not found, falling back to npm"
          npm ci --loglevel=error
        fi
        ;;
      *)
        log "Installing Node.js packages via npm..."
        npm ci --loglevel=error
        ;;
    esac

    # Rebuild native modules
    log "Rebuilding native modules..."
    npm rebuild 2>&1 | tail -5 || true
    ok "Node.js packages installed and native modules rebuilt."
  fi
  echo ""
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo -e "${BOLD}============================================================${RESET}"
if [[ "$ERRORS" -eq 0 ]]; then
  echo -e "${GREEN}${BOLD}  All dependencies installed successfully!${RESET}"
else
  echo -e "${YELLOW}${BOLD}  Dependencies installed with $ERRORS error(s).${RESET}"
  echo -e "  Check the output above for details."
fi
echo -e "${BOLD}============================================================${RESET}"
echo ""
echo -e "  Next steps:"
echo -e "    1. Build the project:  ${CYAN}npm run build${RESET}"
echo -e "    2. Register services:  ${CYAN}sudo ./ops/install.sh${RESET}"
echo ""

exit "$ERRORS"
