#!/usr/bin/env bash
# =============================================================================
# aragonteam — Service status query
# Displays the health of all systemd services, ports, watchdog state,
# recent restart records, and log tails.
#
# Generated by web-deployer skill — 2026-07-20
#
# Usage: ./ops/status.sh          (no sudo required)
# Exit codes: 0 = all OK, 1 = some abnormal, 2 = not installed
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve paths
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.env"

# ---------------------------------------------------------------------------
# Defaults (overridden by config.env if present)
# ---------------------------------------------------------------------------
PROJECT_NAME="aragonteam"
BACKEND_PORT=${BACKEND_PORT:-5000}
FRONTEND_PORT=${FRONTEND_PORT:-3000}
WATCHDOG_FAIL_THRESHOLD=${WATCHDOG_FAIL_THRESHOLD:-5}
WATCHDOG_STATE_DIR=${WATCHDOG_STATE_DIR:-/tmp}

if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck source=config.env
  source "$CONFIG_FILE"
fi

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

if [[ ! -t 1 ]]; then
  RED='' GREEN='' YELLOW='' CYAN='' BOLD='' RESET=''
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
EXIT_CODE=0

print_header() {
  echo ""
  echo -e "${BOLD}============================================================${RESET}"
  echo -e "${BOLD}  ${PROJECT_NAME} Service Status${RESET}"
  echo -e "${BOLD}============================================================${RESET}"
}

print_footer() {
  echo -e "${BOLD}============================================================${RESET}"
  echo ""
}

section() {
  echo ""
  echo -e "  ${BOLD}$1${RESET}"
  echo -e "  ─────────────────────────"
}

kv() {
  local key="$1"
  shift
  printf "  %-14s %b\n" "$key" "$*"
}

# ---------------------------------------------------------------------------
# Pre-flight: check that systemd services are installed
# ---------------------------------------------------------------------------
BACKEND_UNIT="${PROJECT_NAME}-backend.service"
FRONTEND_UNIT="${PROJECT_NAME}-frontend.service"
WATCHDOG_TIMER="${PROJECT_NAME}-watchdog.timer"

check_installed() {
  local missing=0
  local units=()
  units+=("$BACKEND_UNIT")
  units+=("$FRONTEND_UNIT")
  for unit in "${units[@]}"; do
    if ! systemctl list-unit-files "$unit" --no-pager 2>/dev/null | grep -q "$unit"; then
      missing=1
    fi
  done
  if [[ "$missing" -eq 1 ]]; then
    echo ""
    echo -e "  ${YELLOW}${PROJECT_NAME} systemd services are not installed.${RESET}"
    echo -e "  Run ${BOLD}sudo ./ops/install.sh${RESET} to install."
    echo ""
    exit 2
  fi
}

# ---------------------------------------------------------------------------
# Service status helper
# ---------------------------------------------------------------------------
show_service_status() {
  local unit="$1"
  local label="$2"
  local port="$3"
  local health_url="$4"

  section "$label ($unit)"

  local active_state
  active_state=$(systemctl show "$unit" --property=ActiveState --value 2>/dev/null) || active_state="unknown"

  local main_pid
  main_pid=$(systemctl show "$unit" --property=MainPID --value 2>/dev/null) || main_pid="0"

  local status_color="$GREEN"
  if [[ "$active_state" != "active" ]]; then
    status_color="$RED"
    EXIT_CODE=1
  fi

  if [[ "$main_pid" != "0" && -n "$main_pid" ]]; then
    kv "Status:" "${status_color}● ${active_state}${RESET}  PID: ${CYAN}${main_pid}${RESET}"
  else
    kv "Status:" "${status_color}● ${active_state}${RESET}"
  fi

  # Uptime
  local timestamp
  timestamp=$(systemctl show "$unit" --property=ActiveEnterTimestamp --value 2>/dev/null) || timestamp=""
  if [[ -n "$timestamp" && "$timestamp" != "n/a" && "$active_state" == "active" ]]; then
    local since_epoch
    since_epoch=$(date -d "$timestamp" +%s 2>/dev/null) || since_epoch=""
    if [[ -n "$since_epoch" ]]; then
      local now_epoch
      now_epoch=$(date +%s)
      local diff=$((now_epoch - since_epoch))
      local days=$((diff / 86400))
      local hours=$(( (diff % 86400) / 3600 ))
      local mins=$(( (diff % 3600) / 60 ))
      if [[ "$days" -gt 0 ]]; then
        kv "Uptime:" "${days}d ${hours}h ${mins}m"
      elif [[ "$hours" -gt 0 ]]; then
        kv "Uptime:" "${hours}h ${mins}m"
      else
        kv "Uptime:" "${mins}m"
      fi
    fi
  fi

  # Port check
  local port_status
  if ss -tlnH sport = :"$port" 2>/dev/null | grep -q .; then
    port_status="${GREEN}:${port} listening${RESET}"
  else
    port_status="${RED}:${port} not listening${RESET}"
    EXIT_CODE=1
  fi
  kv "Port:" "$port_status"

  # HTTP health check
  local http_code
  http_code=$(curl -sf -o /dev/null -w "%{http_code}" --connect-timeout 3 --max-time 5 "$health_url" 2>/dev/null) || http_code="000"
  if [[ "$http_code" =~ ^2 ]]; then
    kv "Health:" "${GREEN}${health_url} -> ${http_code} OK${RESET}"
  else
    kv "Health:" "${RED}${health_url} -> ${http_code} FAIL${RESET}"
    EXIT_CODE=1
  fi
}

# ---------------------------------------------------------------------------
# Watchdog status
# ---------------------------------------------------------------------------
show_watchdog_status() {
  section "Watchdog ($WATCHDOG_TIMER)"

  local timer_state
  timer_state=$(systemctl show "$WATCHDOG_TIMER" --property=ActiveState --value 2>/dev/null) || timer_state="unknown"

  local timer_sub
  timer_sub=$(systemctl show "$WATCHDOG_TIMER" --property=SubState --value 2>/dev/null) || timer_sub=""

  local timer_color="$GREEN"
  if [[ "$timer_state" != "active" ]]; then
    timer_color="$YELLOW"
  fi

  kv "Status:" "${timer_color}● ${timer_state}${RESET}${timer_sub:+ (${timer_sub})}"

  # Next trigger time
  local next_trigger
  next_trigger=$(systemctl show "$WATCHDOG_TIMER" --property=NextElapseUSecRealtime --value 2>/dev/null) || next_trigger=""
  if [[ -n "$next_trigger" && "$next_trigger" != "n/a" ]]; then
    local next_readable
    next_readable=$(date -d "$next_trigger" '+%Y-%m-%d %H:%M:%S' 2>/dev/null) || next_readable="$next_trigger"
    kv "Next check:" "$next_readable"
  fi

  # Failure counters
  local backend_failures=0
  local counter_file="${WATCHDOG_STATE_DIR}/${PROJECT_NAME}-watchdog-backend-failures"
  if [[ -f "$counter_file" ]]; then
    backend_failures=$(<"$counter_file") || true
    [[ "$backend_failures" =~ ^[0-9]+$ ]] || backend_failures=0
  fi
  local be_color="$GREEN"
  [[ "$backend_failures" -gt 0 ]] && be_color="$YELLOW"
  [[ "$backend_failures" -ge "$WATCHDOG_FAIL_THRESHOLD" ]] && be_color="$RED"
  kv "Backend fails:" "${be_color}${backend_failures}/${WATCHDOG_FAIL_THRESHOLD}${RESET}"

  local frontend_failures=0
  counter_file="${WATCHDOG_STATE_DIR}/${PROJECT_NAME}-watchdog-frontend-failures"
  if [[ -f "$counter_file" ]]; then
    frontend_failures=$(<"$counter_file") || true
    [[ "$frontend_failures" =~ ^[0-9]+$ ]] || frontend_failures=0
  fi
  local fe_color="$GREEN"
  [[ "$frontend_failures" -gt 0 ]] && fe_color="$YELLOW"
  [[ "$frontend_failures" -ge "$WATCHDOG_FAIL_THRESHOLD" ]] && fe_color="$RED"
  kv "Frontend fails:" "${fe_color}${frontend_failures}/${WATCHDOG_FAIL_THRESHOLD}${RESET}"
}

# ---------------------------------------------------------------------------
# Nginx reverse proxy status
# ---------------------------------------------------------------------------
show_nginx_status() {
  section "Nginx Reverse Proxy"

  if ! command -v nginx >/dev/null 2>&1; then
    kv "Status:" "${YELLOW}not installed${RESET}"
    return
  fi

  local nginx_state
  nginx_state=$(systemctl is-active nginx 2>/dev/null) || nginx_state="unknown"
  local nginx_color="$GREEN"
  if [[ "$nginx_state" != "active" ]]; then
    nginx_color="$RED"
    EXIT_CODE=1
  fi
  kv "Status:" "${nginx_color}● ${nginx_state}${RESET}"

  local site_name="${NGINX_SITE_NAME:-${PROJECT_NAME}}"
  local nginx_conf="/etc/nginx/sites-available/$site_name"
  if [[ -f "$nginx_conf" ]]; then
    local domain
    domain=$(grep -oP 'server_name\s+\K[^;]+' "$nginx_conf" 2>/dev/null | head -1 | xargs) || domain=""
    if [[ -n "$domain" ]]; then
      kv "Domain:" "${CYAN}${domain}${RESET}"
    fi

    if grep -q "proxy_buffering off" "$nginx_conf" && grep -q "proxy_read_timeout 3600s" "$nginx_conf"; then
      kv "SSE:" "${GREEN}configured${RESET}"
    else
      kv "SSE:" "${RED}missing proxy_buffering/timeout settings${RESET}"
      EXIT_CODE=1
    fi
  else
    kv "Config:" "${YELLOW}not found at ${nginx_conf}${RESET}"
  fi
}

# ---------------------------------------------------------------------------
# Recent restart records
# ---------------------------------------------------------------------------
show_restart_records() {
  section "Recent Restart Records"

  local unit_args=""
  unit_args="$unit_args -u $BACKEND_UNIT"
  unit_args="$unit_args -u $FRONTEND_UNIT"

  local records
  records=$(journalctl $unit_args \
    --since "7 days ago" --grep "Started\|Stopped\|restart" \
    --no-pager -n 20 --no-hostname 2>/dev/null) || records=""

  if [[ -z "$records" ]]; then
    echo -e "  ${CYAN}(no recent restart records)${RESET}"
  else
    echo "$records" | while IFS= read -r line; do
      echo "  $line"
    done
  fi
}

# ---------------------------------------------------------------------------
# Recent logs
# ---------------------------------------------------------------------------
show_recent_logs() {
  section "Recent Logs (last 5 lines each)"

  echo -e "  ${BOLD}[Backend]${RESET}"
  local backend_logs
  backend_logs=$(journalctl -u "$BACKEND_UNIT" --no-pager -n 5 --no-hostname 2>/dev/null) || backend_logs=""
  if [[ -z "$backend_logs" ]]; then
    echo -e "  ${CYAN}(no logs)${RESET}"
  else
    echo "$backend_logs" | while IFS= read -r line; do
      echo "  $line"
    done
  fi
  echo ""

  echo -e "  ${BOLD}[Frontend]${RESET}"
  local frontend_logs
  frontend_logs=$(journalctl -u "$FRONTEND_UNIT" --no-pager -n 5 --no-hostname 2>/dev/null) || frontend_logs=""
  if [[ -z "$frontend_logs" ]]; then
    echo -e "  ${CYAN}(no logs)${RESET}"
  else
    echo "$frontend_logs" | while IFS= read -r line; do
      echo "  $line"
    done
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
  check_installed
  print_header

  show_service_status "$BACKEND_UNIT" "Backend" "$BACKEND_PORT" \
    "${BACKEND_HEALTH_URL:-http://localhost:${BACKEND_PORT}/health}"

  show_service_status "$FRONTEND_UNIT" "Frontend" "$FRONTEND_PORT" \
    "${FRONTEND_HEALTH_URL:-http://localhost:${FRONTEND_PORT}/}"

  show_watchdog_status
  show_nginx_status
  show_restart_records
  show_recent_logs

  echo ""
  print_footer

  exit "$EXIT_CODE"
}

main
