#!/usr/bin/env bash
# =============================================================================
# aragonteam — Uninstall systemd services
#
# Stops and removes all aragonteam systemd services, watchdog timer,
# logrotate configuration, and Nginx reverse proxy config.
# Does NOT delete project files, logs, or user data.
#
# Generated by web-deployer skill — 2026-07-20
#
# Usage: sudo ./ops/uninstall.sh [--keep-nginx] [--keep-logs]
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly BOLD='\033[1m'
readonly RESET='\033[0m'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()   { echo -e "${CYAN}[$(date '+%H:%M:%S')]${RESET} $*"; }
ok()    { echo -e "${GREEN}[$(date '+%H:%M:%S')] OK${RESET} $*"; }
warn()  { echo -e "${YELLOW}[$(date '+%H:%M:%S')] WARN${RESET} $*"; }
error() { echo -e "${RED}[$(date '+%H:%M:%S')] ERROR${RESET} $*" >&2; }
die()   { error "$*"; exit 1; }

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
KEEP_NGINX=false
KEEP_LOGS=false

for arg in "$@"; do
  case "$arg" in
    --keep-nginx) KEEP_NGINX=true ;;
    --keep-logs)  KEEP_LOGS=true ;;
    --help|-h)
      echo "Usage: sudo $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --keep-nginx  Do not remove Nginx configuration"
      echo "  --keep-logs   Do not suggest log cleanup"
      echo "  --help, -h    Show this help message"
      exit 0
      ;;
    *) warn "Unknown argument: $arg" ;;
  esac
done

# ---------------------------------------------------------------------------
# Step 1: Check sudo
# ---------------------------------------------------------------------------
if [[ "$(id -u)" -ne 0 ]]; then
  die "This script must be run with sudo. Usage: sudo $0"
fi

# ---------------------------------------------------------------------------
# Load configuration
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.env"
if [[ -f "$CONFIG_FILE" ]]; then
  # shellcheck source=config.env
  source "$CONFIG_FILE"
fi
WATCHDOG_STATE_DIR="${WATCHDOG_STATE_DIR:-/tmp}"
PROJECT_NAME="${PROJECT_NAME:-aragonteam}"

echo ""
log "Uninstalling ${PROJECT_NAME} systemd services..."

# ---------------------------------------------------------------------------
# Step 2: Stop services
# ---------------------------------------------------------------------------
log "Stopping services..."
systemctl stop ${PROJECT_NAME}-watchdog.timer   2>/dev/null || true
systemctl stop ${PROJECT_NAME}-watchdog.service 2>/dev/null || true
systemctl stop ${PROJECT_NAME}-frontend.service 2>/dev/null || true
systemctl stop ${PROJECT_NAME}-backend.service  2>/dev/null || true
ok "Services stopped."

# ---------------------------------------------------------------------------
# Step 3: Disable services
# ---------------------------------------------------------------------------
log "Disabling services..."
systemctl disable ${PROJECT_NAME}-watchdog.timer   2>/dev/null || true
systemctl disable ${PROJECT_NAME}-frontend.service 2>/dev/null || true
systemctl disable ${PROJECT_NAME}-backend.service  2>/dev/null || true
ok "Services disabled."

# ---------------------------------------------------------------------------
# Step 4: Remove unit files, logrotate config, and state files
# ---------------------------------------------------------------------------
log "Removing systemd unit files..."
rm -f /etc/systemd/system/${PROJECT_NAME}-backend.service
rm -f /etc/systemd/system/${PROJECT_NAME}-frontend.service
rm -f /etc/systemd/system/${PROJECT_NAME}-watchdog.service
rm -f /etc/systemd/system/${PROJECT_NAME}-watchdog.timer
ok "Unit files removed."

log "Removing logrotate configuration..."
rm -f /etc/logrotate.d/${PROJECT_NAME}
ok "Logrotate config removed."

log "Removing watchdog state files..."
rm -f "$WATCHDOG_STATE_DIR/${PROJECT_NAME}-watchdog-backend-failures"
rm -f "$WATCHDOG_STATE_DIR/${PROJECT_NAME}-watchdog-frontend-failures"
rm -f "$WATCHDOG_STATE_DIR/${PROJECT_NAME}-watchdog.lock"
ok "Watchdog state files removed."

# ---------------------------------------------------------------------------
# Step 5: Remove Nginx configuration (unless --keep-nginx)
# ---------------------------------------------------------------------------
if [[ "$KEEP_NGINX" == false ]]; then
  NGINX_SITE_NAME="${NGINX_SITE_NAME:-${PROJECT_NAME}}"
  if [[ -e "/etc/nginx/sites-enabled/$NGINX_SITE_NAME" || -e "/etc/nginx/sites-available/$NGINX_SITE_NAME" ]]; then
    log "Removing Nginx reverse proxy configuration..."
    rm -f "/etc/nginx/sites-enabled/$NGINX_SITE_NAME"
    rm -f "/etc/nginx/sites-available/$NGINX_SITE_NAME"
    rm -f /etc/nginx/sites-available/${NGINX_SITE_NAME}.bak.* 2>/dev/null || true
    if command -v nginx >/dev/null 2>&1 && nginx -t 2>/dev/null; then
      systemctl reload nginx 2>/dev/null || true
    fi
    ok "Nginx config removed."
  else
    ok "No Nginx config found — skipping."
  fi
else
  warn "Keeping Nginx configuration (--keep-nginx)."
fi

# ---------------------------------------------------------------------------
# Step 6: Reload systemd
# ---------------------------------------------------------------------------
log "Reloading systemd daemon..."
systemctl daemon-reload
ok "systemd daemon reloaded."

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}============================================================${RESET}"
echo -e "${GREEN}${BOLD}  ${PROJECT_NAME} systemd services uninstalled${RESET}"
echo -e "${BOLD}============================================================${RESET}"
echo -e "  ${YELLOW}Note:${RESET} Project files, logs, and user data were NOT deleted."
if [[ "$KEEP_LOGS" == false ]]; then
  echo -e "  To remove them manually:"
  echo -e "    rm -rf <project-dir>/logs/"
  echo -e "    rm -rf ~/.${PROJECT_NAME}-data/"
fi
echo -e "${BOLD}============================================================${RESET}"
echo ""
